// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pedido.Infra.Contexts;

#nullable disable

namespace Pedido.Infra.Migrations
{
    [DbContext(typeof(PedidoContext))]
    [Migration("20240105014547_Produto")]
    partial class Produto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pedido.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<sbyte>("Ativo")
                        .HasColumnType("Tinyint")
                        .HasColumnName("Ativo");

                    b.Property<string>("Cor")
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Cor");

                    b.Property<string>("Descricao")
                        .HasColumnType("Text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(255)")
                        .HasColumnName("Nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("Int")
                        .HasColumnName("Quantidade");

                    b.Property<decimal>("ValorUni")
                        .HasColumnType("Decimal(9,2)")
                        .HasColumnName("ValorUni");

                    b.HasKey("Id");

                    b.ToTable("Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
